const icons={Dog:'🐶',Cat:'🐱',Rabbit:'🐰'};
export class UIManager {
  constructor(game){this.game=game;this.toastTimer=null;document.querySelector('#prompt').addEventListener('click',()=>this.game.interact(this.game.currentTarget));}
  showHUD(){document.querySelector('#hud').classList.remove('hidden')}
  refresh(){const {economy,objectives}=this.game;document.querySelector('#money').textContent=`$${economy.money}`;document.querySelector('#reputation').textContent=economy.reputation.toFixed(1);document.querySelector('#adoptions').textContent=economy.adoptions;document.querySelector('#objective-count').textContent=`${objectives.items.filter(i=>i.done).length}/5`;document.querySelector('#objective-list').innerHTML=objectives.items.map(i=>`<div class="objective ${i.done?'done':''}"><i>${i.done?'✓':''}</i><span>${i.label}</span></div>`).join('')}
  prompt(text){const el=document.querySelector('#prompt');el.innerHTML=text?`<kbd>E</kbd>${text}`:'';el.classList.toggle('hidden',!text)}
  toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.remove('hidden');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>el.classList.add('hidden'),1900)}
  close(){document.querySelector('#modal-root').innerHTML='';this.game.scene.scene.resume();}
  shell(body){this.game.scene.scene.pause();document.querySelector('#modal-root').innerHTML=`<div class="modal-backdrop"><section class="modal">${body}</section></div>`;document.querySelector('.close')?.addEventListener('click',()=>this.close())}
  profile(animal){this.game.objectives.complete('profile');this.refresh();const needs=[['Hunger',animal.hunger],['Cleanliness',animal.cleanliness],['Happiness',animal.happiness],['Health',animal.health]];this.shell(`<header><h2><small>ANIMAL PROFILE</small>${animal.name}</h2><button class="close" aria-label="Close">×</button></header><div class="profile-grid"><div class="animal-portrait">${icons[animal.species]}</div><div><div class="meta"><b>${animal.species}</b><span>${animal.age} ${animal.age===1?'year':'years'} old</span></div><div>${animal.traits.map(t=>`<span class="trait">${t}</span>`).join('')}</div>${needs.map(([n,v])=>`<div class="need"><span>${n}</span><div class="bar"><i style="width:${v}%"></i></div><b>${Math.round(v)}</b></div>`).join('')}</div></div><div class="actions"><button data-care="feed">Feed · $3</button><button data-care="clean">Clean · $2</button><button data-care="play">Play · Free</button><button data-care="medicate" ${animal.medicationNeeded?'':'disabled'}>Medicine · $5</button></div>`);document.querySelectorAll('[data-care]').forEach(b=>b.addEventListener('click',()=>this.game.care(animal,b.dataset.care)))}
  adoption(visitor,animals){this.shell(`<header><h2><small>ADOPTION DESK</small>Find a great match</h2><button class="close">×</button></header><div class="adopter-card"><b>${visitor.name} is ready to adopt</b><p>Looking for a <b>${visitor.species}</b> who is <b>${visitor.activity.toLowerCase()}</b> or <b>${visitor.wish.toLowerCase()}</b>.</p></div>${animals.map(a=>`<div class="animal-choice"><span class="face">${icons[a.species]}</span><span><b>${a.name}</b><small>${a.species} · ${a.traits.join(' & ')}</small></span><button class="adopt-button" data-adopt="${a.id}">Recommend</button></div>`).join('')}`);document.querySelectorAll('[data-adopt]').forEach(b=>b.addEventListener('click',()=>this.game.completeAdoption(+b.dataset.adopt)))}
  adoptionResult(animal,score,reward){const label=score>=75?'A perfect match!':score>=50?'A happy match!':'A hopeful new start';document.querySelector('.modal').innerHTML=`<div class="match-result"><div class="big">${icons[animal.species]} ♥ 🏠</div><h3>${label}</h3><p>${animal.name} has gone home.<br/><b>+$${reward} funding · Match score ${score}%</b></p><button class="adopt-button close-result">Back to the shelter</button></div>`;document.querySelector('.close-result').addEventListener('click',()=>this.close())}
}

