import {ENRICHMENT_ITEMS} from '../systems/EnrichmentSystem.js';
const icons={Dog:'🐶',Cat:'🐱',Rabbit:'🐰'};
export class UIManager{
 constructor(app){this.app=app;this.toastTimer=null;this.taskOpen=false;document.querySelector('#prompt').addEventListener('click',()=>app.interact(app.currentTarget));document.querySelector('#tasks-toggle').addEventListener('click',()=>this.toggleTasks());document.querySelector('#tasks-close').addEventListener('click',()=>this.toggleTasks(false));}
 showHUD(){document.querySelector('#hud').classList.remove('hidden')}
 toggleTasks(force){this.taskOpen=force??!this.taskOpen;document.querySelector('#objectives-panel').classList.toggle('collapsed',!this.taskOpen);document.querySelector('#tasks-toggle').setAttribute('aria-expanded',String(this.taskOpen))}
 refresh(){const {economy,objectives}=this.app;const done=objectives.items.filter(i=>i.done).length;document.querySelector('#money').textContent=`$${economy.money}`;document.querySelector('#reputation').textContent=economy.reputation.toFixed(1);document.querySelector('#adoptions').textContent=economy.adoptions;document.querySelector('#objective-count').textContent=`${done}/5`;document.querySelector('#task-badge').textContent=5-done;document.querySelector('#objective-list').innerHTML=objectives.items.map(i=>`<div class="objective ${i.done?'done':''}"><i>${i.done?'✓':''}</i><span>${i.label}</span></div>`).join('')}
 prompt(text){const el=document.querySelector('#prompt');el.innerHTML=text?`<kbd>E</kbd>${text}`:'';el.classList.toggle('hidden',!text)}
 toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.remove('hidden');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>el.classList.add('hidden'),2100)}
 close(){document.querySelector('#modal-root').innerHTML='';this.app.scene.scene.resume()}
 shell(body,wide=false){this.app.scene.scene.pause();document.querySelector('#modal-root').innerHTML=`<div class="modal-backdrop"><section class="modal ${wide?'wide':''}">${body}</section></div>`;document.querySelector('.close')?.addEventListener('click',()=>this.close())}
 profile(animal){this.app.objectives.complete('profile');this.refresh();const needs=[['Hunger',animal.hunger],['Cleanliness',animal.cleanliness],['Happiness',animal.happiness],['Health',animal.health]];const enrichment=animal.enrichment.length?animal.enrichment.map(id=>ENRICHMENT_ITEMS.find(i=>i.id===id)?.name).join(', '):'No enrichment placed';this.shell(`<header><h2><small>ANIMAL PROFILE</small>${animal.name}</h2><button class="close" aria-label="Close">×</button></header><div class="profile-grid"><div class="animal-portrait">${icons[animal.species]}<small class="pixel-note">${animal.appearance.id.toUpperCase()}</small></div><div><div class="meta"><b>${animal.species}</b><span>${animal.age} ${animal.age===1?'year':'years'} old</span></div><div>${animal.traits.map(t=>`<span class="trait">${t}</span>`).join('')}</div>${needs.map(([n,v])=>`<div class="need"><span>${n}</span><div class="bar"><i style="width:${v}%"></i></div><b>${Math.round(v)}</b></div>`).join('')}<div class="enrichment-row"><b>Enrichment:</b> ${enrichment}</div></div></div><div class="actions"><button data-care="feed">Feed · $3</button><button data-care="clean">Clean · $2</button><button data-care="play">Play · Free</button><button data-care="medicate" ${animal.medicationNeeded?'':'disabled'}>Medicine · $5</button></div>`);document.querySelectorAll('[data-care]').forEach(b=>b.addEventListener('click',()=>this.app.care(animal,b.dataset.care)))}
 adoption(visitor,animals){this.shell(`<header><h2><small>ADOPTION DESK</small>Find a great match</h2><button class="close">×</button></header><div class="adopter-card"><b>${visitor.name} is ready to adopt</b><p>Looking for a <b>${visitor.species}</b> who is <b>${visitor.activity.toLowerCase()}</b> or <b>${visitor.wish.toLowerCase()}</b>.</p></div>${animals.map(a=>`<div class="animal-choice"><span class="face">${icons[a.species]}</span><span><b>${a.name}</b><small>${a.species} · ${a.traits.join(' & ')} · ${a.appearance.id}</small></span><button class="adopt-button" data-adopt="${a.id}">Recommend</button></div>`).join('')}`);document.querySelectorAll('[data-adopt]').forEach(b=>b.addEventListener('click',()=>this.app.completeAdoption(+b.dataset.adopt)))}
 adoptionResult(animal,score,reward){const label=score>=75?'A perfect match!':score>=50?'A happy match!':'A hopeful new start';document.querySelector('.modal').innerHTML=`<div class="match-result"><div class="big">${icons[animal.species]} ♥ 🏠</div><h3>${label}</h3><p>${animal.name} has gone home.<br/><b>+$${reward} funding · Match score ${score}%</b></p><button class="adopt-button close-result">Back to the shelter</button></div>`;document.querySelector('.close-result').addEventListener('click',()=>this.close())}
 computer(tab='intake'){const {intake}=this.app;this.shell(`<header><h2><small>PAW HAVEN TERMINAL</small>Shelter management</h2><span class="capacity ${intake.full?'full':''}">ANIMALS ${intake.count} / ${intake.capacity}</span><button class="close">×</button></header><nav class="tabs"><button data-tab="intake" class="${tab==='intake'?'active':''}">INTAKE QUEUE</button><button data-tab="shop" class="${tab==='shop'?'active':''}">ENRICHMENT SHOP</button><button data-tab="inventory" class="${tab==='inventory'?'active':''}">PLACE ITEMS</button></nav><div id="computer-content"></div>`,true);document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>this.computer(b.dataset.tab)));if(tab==='intake')this.renderIntake();if(tab==='shop')this.renderShop();if(tab==='inventory')this.renderInventory()}
 renderIntake(){const {intake}=this.app;const root=document.querySelector('#computer-content');root.innerHTML=intake.pending.length?intake.pending.map(a=>`<article class="intake-card"><div class="intake-face">${icons[a.species]}</div><div><b>${a.name} · ${a.species} · ${a.age} yrs</b><p>${a.traits.join(' & ')} · ${a.appearance.id}</p><p><b>Health:</b> ${a.healthNote}</p><p><b>Reason:</b> ${a.reason}</p></div><div class="decision"><button data-accept="${a.id}" ${intake.full?'disabled':''}>ACCEPT INTAKE</button><button class="decline" data-decline="${a.id}">DECLINE</button></div></article>`).join(''):`<div class="empty-state"><b>No pending intakes</b><p>New requests arrive periodically.</p></div>`;document.querySelectorAll('[data-accept]').forEach(b=>b.addEventListener('click',()=>this.app.acceptIntake(+b.dataset.accept)));document.querySelectorAll('[data-decline]').forEach(b=>b.addEventListener('click',()=>this.app.declineIntake(+b.dataset.decline)))}
 renderShop(){document.querySelector('#computer-content').innerHTML=`<div class="shop-grid">${ENRICHMENT_ITEMS.map(i=>`<article class="shop-card"><span class="item-icon">${i.icon}</span><span><b>${i.name}</b><small>${i.species.join(' / ')} · ${i.benefit}</small></span><button data-buy="${i.id}">$${i.price}</button></article>`).join('')}</div>`;document.querySelectorAll('[data-buy]').forEach(b=>b.addEventListener('click',()=>this.app.buyEnrichment(b.dataset.buy)))}
 renderInventory(){const {enrichment,animals}=this.app;const root=document.querySelector('#computer-content');if(!enrichment.inventory.length){root.innerHTML='<div class="empty-state"><b>Your supply cart is empty</b><p>Purchase enrichment in the shop first.</p></div>';return}root.innerHTML=enrichment.inventory.map((id,index)=>{const item=ENRICHMENT_ITEMS.find(i=>i.id===id);return`<div class="animal-choice"><span class="item-icon">${item.icon}</span><span><b>${item.name}</b><small>Choose an appropriate resident</small></span><span>${animals.animals.filter(a=>item.species.includes(a.species)&&a.enrichment.length<2).map(a=>`<button class="place-button" data-place="${index}" data-animal="${a.id}">${a.name}</button>`).join(' ')||'No open slot'}</span></div>`}).join('');document.querySelectorAll('[data-place]').forEach(b=>b.addEventListener('click',()=>this.app.placeEnrichment(+b.dataset.place,+b.dataset.animal)))}
}

