import Phaser from 'phaser';
const C={floor:0xeee4c6,wall:0x214b42,trim:0xc46b52,dog:0xd5a36a,cat:0xb1a2d2,rabbit:0x8ebc9a};
export class ShelterScene extends Phaser.Scene{
  constructor(){super('Shelter')}
  create(){this.physics.world.setBounds(22,22,1156,676);this.drawShelter();this.createAnimals();this.createPlayer();this.keys=this.input.keyboard.addKeys('W,A,S,D,E');this.cursors=this.input.keyboard.createCursorKeys();this.lastInteract=0;this.tapDirection=new Phaser.Math.Vector2();this.tapUntil=0;
    // A brief movement impulse makes quick key taps feel responsive, while held
    // keys still use the normal smooth movement in update().
    this.input.keyboard.on('keydown',event=>{const directions={ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0],ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1]};const d=directions[event.key];if(d){this.tapDirection.set(d[0],d[1]);this.tapUntil=this.time.now+95}});
    this.gameReady=true;this.time.addEvent({delay:4000,loop:true,callback:()=>{this.game.app.animals.tick();this.game.app.ui.refresh()}})}
  rect(x,y,w,h,color,stroke=C.wall){const r=this.add.rectangle(x,y,w,h,color).setStrokeStyle(3,stroke);this.physics.add.existing(r,true);return r}
  label(x,y,text,sub){this.add.text(x,y,text,{fontFamily:'Nunito',fontSize:'17px',fontStyle:'bold',color:'#214b42'}).setOrigin(.5);if(sub)this.add.text(x,y+20,sub,{fontFamily:'DM Mono',fontSize:'8px',color:'#6c7867'}).setOrigin(.5)}
  drawShelter(){this.add.rectangle(600,360,1200,720,C.floor);for(let x=0;x<1200;x+=40)this.add.line(0,0,x,0,x,720,0xd8cfb3,.25).setOrigin(0);this.walls=this.physics.add.staticGroup();[[600,10,1200,20],[600,710,1200,20],[10,360,20,720],[1190,360,20,720],[410,190,12,300],[790,190,12,300],[410,565,12,280],[790,565,12,280]].forEach(([x,y,w,h])=>this.walls.add(this.add.rectangle(x,y,w,h,C.wall)));
    this.add.rectangle(205,190,380,280,0xe5d2a7).setStrokeStyle(4,C.wall);this.add.rectangle(600,190,360,280,0xd8e3cc).setStrokeStyle(4,C.wall);this.add.rectangle(995,190,380,280,0xe7d7df).setStrokeStyle(4,C.wall);this.label(205,58,'DOG LODGE','WAGGING WELCOME');this.label(600,58,'BUNNY BURROW','QUIET & COZY');this.label(995,58,'CAT CORNER','SUNBEAM CLUB');
    this.objects=[];this.addObject(135,520,130,95,0xc97955,'Food pantry','Restock & feed','food');this.addObject(275,520,130,95,0x78a69b,'Wash station','Fresh towels','cleaning');this.addObject(600,570,245,105,0xe3b95d,'Adoption desk','New visitor waiting','desk');this.add.rectangle(995,560,240,150,0xb7c69c).setStrokeStyle(3,C.wall);this.label(995,535,'WELCOME LOUNGE','MEET YOUR NEW FAMILY');this.add.text(600,680,'WASD / ARROWS  MOVE     E  INTERACT',{fontFamily:'DM Mono',fontSize:'10px',color:'#657567'}).setOrigin(.5)}
  addObject(x,y,w,h,color,label,sub,type){const o=this.add.rectangle(x,y,w,h,color).setStrokeStyle(3,C.wall);this.physics.add.existing(o,true);o.kind='object';o.type=type;o.label=label;this.objects.push(o);this.label(x,y-5,label.toUpperCase(),sub)}
  createAnimals(){this.animalSprites=[];const spots={Dog:[210,200],Rabbit:[600,200],Cat:[995,200]};this.game.app.animals.animals.forEach(a=>this.spawnAnimal(a,spots[a.species]))}
  spawnAnimal(animal,[x,y]){const colors={Dog:C.dog,Cat:C.cat,Rabbit:C.rabbit};const g=this.add.container(x,y);const shadow=this.add.ellipse(0,20,60,24,0x173d36,.15);const body=this.add.ellipse(0,0,53,45,colors[animal.species]).setStrokeStyle(3,C.wall);const ears=animal.species==='Rabbit'?[this.add.ellipse(-13,-30,13,42,colors[animal.species]).setStrokeStyle(2,C.wall),this.add.ellipse(13,-30,13,42,colors[animal.species]).setStrokeStyle(2,C.wall)]:[this.add.triangle(-18,-19,-12,10,0,-12,12,10,colors[animal.species]).setStrokeStyle(2,C.wall),this.add.triangle(18,-19,-12,10,0,-12,12,10,colors[animal.species]).setStrokeStyle(2,C.wall)];const face=this.add.text(0,-2,'• ᴥ •',{fontSize:'13px',color:'#173d36'}).setOrigin(.5);const name=this.add.text(0,38,animal.name.toUpperCase(),{fontFamily:'DM Mono',fontSize:'9px',backgroundColor:'#fbf5df',color:'#173d36',padding:{x:6,y:3}}).setOrigin(.5);g.add([shadow,...ears,body,face,name]);this.physics.add.existing(g);g.body.setCircle(30,-30,-30).setImmovable();g.kind='animal';g.animal=animal;this.animalSprites.push(g);this.tweens.add({targets:g,y:y-5,duration:1200+Math.random()*500,yoyo:true,repeat:-1,ease:'Sine.inOut'})}
  createPlayer(){const g=this.add.container(600,430);const shadow=this.add.ellipse(0,18,38,18,0x173d36,.18);const body=this.add.rectangle(0,2,28,35,0xd96650).setStrokeStyle(3,C.wall);const head=this.add.circle(0,-21,16,0xe2ad7d).setStrokeStyle(3,C.wall);const hair=this.add.arc(0,-25,15,180,360,false,0x493a33);g.add([shadow,body,head,hair]);this.physics.add.existing(g);g.body.setSize(28,50).setOffset(-14,-28).setCollideWorldBounds(true);this.player=g;this.physics.add.collider(g,this.walls);this.objects.forEach(o=>this.physics.add.collider(g,o));this.animalSprites.forEach(a=>this.physics.add.collider(g,a))}
  nearest(){let candidates=[...this.animalSprites,...this.objects];let best=null,dist=92;for(const c of candidates){const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,c.x,c.y);if(d<dist){best=c;dist=d}}return best}
  update(time){if(!this.player||this.scene.isPaused())return;let x=0,y=0;if(this.keys.A.isDown||this.cursors.left.isDown)x=-1;if(this.keys.D.isDown||this.cursors.right.isDown)x=1;if(this.keys.W.isDown||this.cursors.up.isDown)y=-1;if(this.keys.S.isDown||this.cursors.down.isDown)y=1;if(x===0&&y===0&&time<this.tapUntil){x=this.tapDirection.x;y=this.tapDirection.y}const v=new Phaser.Math.Vector2(x,y).normalize().scale(185);this.player.body.setVelocity(v.x,v.y);const target=this.nearest();this.game.app.currentTarget=target;this.game.app.ui.prompt(target?(target.kind==='animal'?`Meet ${target.animal.name}`:target.type==='desk'?'Talk to the adopter':target.label):'')}
}
