import Phaser from 'phaser';
import {TILE_SIZE,COLS,ROWS,WORLD,PENS,OBJECTS,VIEWING,SAFE_WAIT,DESTINATIONS,worldCenter,rectCells} from '../data/shelterGrid.js';
import {animalWalkColumn} from '../systems/AnimationSystem.js';
import {FURNITURE_CATALOG} from '../systems/FurnitureSystem.js';
const ROW={Dog:{golden:0,black:1,brown:2,spotted:3},Cat:{tuxedo:0,tabby:1,gray:2,calico:3},Rabbit:{white:0,brown:1,spotted:2,gray:3}};
const META={Dog:{texture:'dogs',cols:12,size:64,radius:22,speed:34},Cat:{texture:'cats',cols:12,size:49,radius:17,speed:38},Rabbit:{texture:'rabbits',cols:13,size:37,radius:13,speed:42}};
const ITEM={'tennis-ball':0,'dog-chew':1,'dog-bed':6,'dog-puzzle':7,'scratching-post':2,'cat-tower':2,'cat-toy':3,'cat-bed':6,'cat-puzzle':7,'rabbit-tunnel':4,'rabbit-chew':5,'rabbit-hideout':4,'rabbit-mat':6,'rabbit-puzzle':7};
export class ShelterScene extends Phaser.Scene{
 constructor(){super('Shelter')}
 preload(){this.load.image('floor','./assets/environment/v3/floor.png');this.load.image('structure','./assets/environment/v3/structure-back.png');for(const o of OBJECTS)this.load.image(o.id,`./assets/objects/${o.id}.png`);for(const o of FURNITURE_CATALOG)if(!this.textures.exists(o.texture))this.load.image(o.texture,`./assets/objects/${o.texture}.png`);this.load.image('bowl-water','./assets/objects/bowl-water.png');this.load.image('bowl-food','./assets/objects/bowl-food.png');this.load.image('fences','./assets/environment/v3/pen-foreground.png');this.load.spritesheet('dogs','./assets/sprites/dogs-actions.png',{frameWidth:180,frameHeight:222});this.load.spritesheet('cats','./assets/sprites/cats-actions.png',{frameWidth:200,frameHeight:222});this.load.spritesheet('rabbits','./assets/sprites/rabbits-actions.png',{frameWidth:160,frameHeight:256});this.load.spritesheet('player-actions','./assets/sprites/player-actions.png',{frameWidth:270,frameHeight:724});this.load.spritesheet('npc-actions','./assets/sprites/npc-actions.png',{frameWidth:170,frameHeight:256});this.load.spritesheet('items','./assets/items/enrichment-atlas.png',{frameWidth:362,frameHeight:362})}
 create(){this.grid=this.game.app.grid;this.add.image(WORLD.width/2,WORLD.height/2,'floor').setDisplaySize(WORLD.width,WORLD.height);this.add.image(WORLD.width/2,WORLD.height/2,'structure').setDisplaySize(WORLD.width,WORLD.height).setDepth(40);this.physics.world.setBounds(0,0,WORLD.width,WORLD.height);this.objects=[];this.animalSprites=[];this.visitors=[];this.enrichmentSprites=[];this.viewReservations=new Map();this.debugEnabled=false;this.createGridCollision();this.createObjects();this.createAnimals();this.createPlayer();this.setupBuildControls();this.add.image(WORLD.width/2,WORLD.height/2,'fences').setDisplaySize(WORLD.width,WORLD.height).setDepth(900);this.keys=this.input.keyboard.addKeys('W,A,S,D');this.cursors=this.input.keyboard.createCursorKeys();this.tapDirection=new Phaser.Math.Vector2();this.tapUntil=0;this.input.keyboard.on('keydown',e=>{const d={ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0],ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1]}[e.key];if(d){this.tapDirection.set(...d);this.tapUntil=this.time.now+110}});this.input.keyboard.on('keydown-F2',()=>this.toggleDebug());this.time.addEvent({delay:4000,loop:true,callback:()=>{this.game.app.animals.tick(1,this.game.app.pens);this.game.app.ui.refresh()}});this.time.addEvent({delay:22000,loop:true,callback:()=>this.game.app.queueIntake()});this.time.delayedCall(1800,()=>this.spawnVisitor(true));this.time.addEvent({delay:9000,loop:true,callback:()=>{if(this.visitors.length<5)this.spawnVisitor(Math.random()<.35)}})}
 createGridCollision(){for(const c of this.collisionLinks||[])c.destroy();for(const z of this.collisionZones||[])z.destroy();this.walls?.clear(true,true);this.walls=this.physics.add.staticGroup();this.collisionDefs=[];this.collisionZones=[];this.collisionLinks=[];for(const t of this.grid.blockedCells()){if(t.type==='gate')continue;const p=this.grid.center(t.c,t.r),z=this.add.zone(p.x,p.y,TILE_SIZE,TILE_SIZE);this.physics.add.existing(z,true);this.walls.add(z);this.collisionZones.push(z);this.collisionDefs.push(t)}if(this.player)this.collisionLinks.push(this.physics.add.collider(this.player,this.walls));for(const v of this.visitors)this.collisionLinks.push(this.physics.add.collider(v,this.walls))}
 createObjects(){this.furnitureSprites=new Map();for(const p of Object.values(PENS))for(const b of p.bowls){const pos=this.grid.center(b.c,b.r);this.add.image(pos.x,pos.y,b.kind==='food'?'bowl-food':'bowl-water').setDisplaySize(28,22).setDepth(100+pos.y)}for(const o of this.game.app.furniture.placed)this.renderFurniture(o);for(const o of this.game.app.furniture.placed.filter(o=>o.fixed&&o.label)){const p=worldCenter(o.c+(o.w-1)/2,o.r+(o.h-1)/2),z=this.add.zone(p.x,p.y,o.w*TILE_SIZE,o.h*TILE_SIZE);z.kind='object';z.type=o.type;z.label=o.label;z.gridObject=o;this.objects.push(z)}}
 renderFurniture(o){const centerX=(o.c+o.w/2)*TILE_SIZE,bottomY=(o.r+o.h)*TILE_SIZE,s=this.add.image(centerX,bottomY,o.texture).setOrigin(.5,1).setDisplaySize(o.display.w,o.display.h).setAngle(o.rotation||0).setDepth(o.blocking===false?65:200+bottomY);s.furniture=o;this.furnitureSprites.set(o.instanceId,s);return s}
 createAnimals(){this.animalGroup=this.physics.add.group();for(const a of this.game.app.animals.animals)this.spawnAnimal(a,this.openSpot(a.species));for(const p of Object.values(this.game.app.pens.pens))for(const i of p.installed)this.showInstalledEnrichment(i)}
 openSpot(species){const pen=this.game.app.pens.penFor(species),same=this.animalSprites.filter(s=>s.animal.species===species),choices=Phaser.Utils.Array.Shuffle([...pen.interiorCells]);const chosen=choices.find(t=>same.every(s=>{const c=this.grid.cell(s.x,s.y);return Math.abs(t.c-c.c)+Math.abs(t.r-c.r)>1}))||choices[0];const p=this.grid.center(chosen.c,chosen.r);return[p.x,p.y]}
 spawnAnimal(animal,[x,y]){const m=META[animal.species],base=(ROW[animal.species][animal.appearance.id]??0)*m.cols,scale=.94+Math.random()*.12,s=this.physics.add.sprite(x,y,m.texture,base).setDisplaySize(m.size*scale,m.size*scale);s.body.setCircle(m.radius*.7,undefined,m.radius*.58);s.kind='animal';s.animal=animal;s.bodyRadius=m.radius;s.meta=m;s.baseFrame=base;s.brain={state:'idle',until:this.time.now+1000+Math.random()*3000,path:[],pathIndex:0,reservation:null,frameAt:0,toggle:0};this.animalSprites.push(s);this.animalGroup.add(s);this.physics.add.collider(s,this.animalGroup);return s}
 createPlayer(){const s=this.physics.add.sprite(624,688,'player-actions',0).setDisplaySize(52,78);s.body.setSize(76,55).setOffset(97,650).setCollideWorldBounds(true);this.player=s;this.physics.add.collider(s,this.walls)}
 setupBuildControls(){this.buildMode=false;this.buildSelection=null;this.buildGraphics=this.add.graphics().setDepth(1900);this.input.on('pointerdown',p=>{if(this.buildMode)this.handleBuildClick(p)});this.input.on('pointermove',p=>{if(this.buildMode&&this.buildSelection)this.updateBuildPreview(p)});this.input.on('wheel',(_p,_o,_x,y)=>{if(this.buildMode)this.cameras.main.setZoom(Phaser.Math.Clamp(this.cameras.main.zoom-y*.001,1,1.8))});this.input.keyboard.on('keydown-B',()=>this.toggleBuildMode());this.input.keyboard.on('keydown-R',()=>this.rotateBuildSelection());this.input.keyboard.on('keydown-ESC',()=>this.cancelBuildSelection());this.input.keyboard.on('keydown-DELETE',()=>this.storeBuildSelection());this.input.keyboard.on('keydown-PLUS',()=>{if(this.buildMode)this.cameras.main.setZoom(Math.min(1.8,this.cameras.main.zoom+.1))});this.input.keyboard.on('keydown-MINUS',()=>{if(this.buildMode)this.cameras.main.setZoom(Math.max(1,this.cameras.main.zoom-.1))})}
 toggleBuildMode(force){this.buildMode=force??!this.buildMode;if(!this.buildMode)this.cancelBuildSelection();this.player.setVelocity(0);for(const v of this.visitors)v.setVelocity(0);for(const a of this.animalSprites)a.setVelocity(0);this.game.app.ui.setBuildMode(this.buildMode);this.drawBuildOverlay();if(!this.buildMode){this.cameras.main.setZoom(1);this.cameras.main.centerOn(WORLD.width/2,WORLD.height/2)}else this.game.app.ui.toast('Build Mode: select furniture or choose an inventory item.')}
 selectInventoryFurniture(id){if(!this.buildMode)return;this.cancelBuildSelection();const f=this.game.app.furniture,item=f.item(id);if(!item||f.count(id)<1)return;this.buildSelection={source:'inventory',placement:f.createPlacement(id,18,16,0),sprite:null};this.game.app.ui.buildStatus(`Placing ${item.name} · click a green location`);this.drawBuildOverlay()}
 handleBuildClick(pointer){const w=pointer.positionToCamera(this.cameras.main),cell=this.grid.cell(w.x,w.y),f=this.game.app.furniture;if(this.buildSelection){this.buildSelection.placement.c=cell.c;this.buildSelection.placement.r=cell.r;if(!f.canPlace(this.buildSelection.placement))return this.game.app.ui.toast('Invalid placement: blocked or disconnects a required route.');const b=this.buildSelection;if(!f.place(b.placement,b.source==='inventory'))return;this.furnitureSprites.get(b.placement.instanceId)?.destroy();this.renderFurniture(b.placement);this.buildSelection=null;this.afterFurnitureChange('Furniture placed.');return}const placed=[...f.placed].reverse().find(o=>f.cells(o).some(t=>t.c===cell.c&&t.r===cell.r));if(!placed)return;if(!placed.movable)return this.game.app.ui.toast('That object is fixed and required for shelter operations.');const sprite=this.furnitureSprites.get(placed.instanceId),original=f.pickUp(placed.instanceId);sprite?.setVisible(false);this.buildSelection={source:'existing',placement:{...original,display:{...original.display}},original,sprite};this.createGridCollision();this.game.app.ui.buildStatus(`Moving ${f.item(placed.catalogId)?.name||'furniture'} · click to place`);this.drawBuildOverlay()}
 updateBuildPreview(pointer){const w=pointer.positionToCamera(this.cameras.main),c=this.grid.cell(w.x,w.y);this.buildSelection.placement.c=c.c;this.buildSelection.placement.r=c.r;this.drawBuildOverlay()}
 rotateBuildSelection(){const b=this.buildSelection,f=this.game.app.furniture;if(!b||!b.placement.rotatable)return;const p=b.placement;p.rotation=(p.rotation+90)%360;[p.w,p.h]=[p.h,p.w];this.drawBuildOverlay()}
 cancelBuildSelection(){const b=this.buildSelection;if(!b)return;if(b.source==='existing'){this.game.app.furniture.restore(b.original);b.sprite?.setVisible(true)}this.buildSelection=null;this.createGridCollision();this.drawBuildOverlay();this.game.app.ui.buildStatus('Select furniture or choose an inventory item')}
 storeBuildSelection(){const b=this.buildSelection;if(!b||b.source!=='existing')return;this.game.app.furniture.store(b.original);b.sprite?.destroy();this.furnitureSprites.delete(b.placement.instanceId);this.buildSelection=null;this.afterFurnitureChange('Furniture returned to inventory.')}
 afterFurnitureChange(message){this.createGridCollision();for(const v of this.visitors)if(v.currentGoal)this.setVisitorPath(v,v.currentGoal);this.game.app.ui.renderFurnitureInventory();this.game.app.ui.buildStatus('Select furniture or choose an inventory item');this.game.app.ui.toast(message);this.drawBuildOverlay()}
 drawBuildOverlay(){const g=this.buildGraphics;if(!g)return;g.clear();if(!this.buildMode){this.buildPreview?.destroy();this.buildPreview=null;return}g.lineStyle(1,0x9ad8c1,.25);for(let c=0;c<=COLS;c++)g.lineBetween(c*TILE_SIZE,0,c*TILE_SIZE,WORLD.height);for(let r=0;r<=ROWS;r++)g.lineBetween(0,r*TILE_SIZE,WORLD.width,r*TILE_SIZE);if(this.buildSelection){const p=this.buildSelection.placement,valid=this.game.app.furniture.canPlace(p),centerX=(p.c+p.w/2)*TILE_SIZE,bottomY=(p.r+p.h)*TILE_SIZE;g.fillStyle(valid?0x58d68d:0xe74c3c,.35);for(const t of this.game.app.furniture.cells(p))g.fillRect(t.c*TILE_SIZE,t.r*TILE_SIZE,TILE_SIZE,TILE_SIZE);g.lineStyle(3,valid?0x7dffad:0xff6357,1);g.strokeRect(p.c*TILE_SIZE,p.r*TILE_SIZE,p.w*TILE_SIZE,p.h*TILE_SIZE);if(!this.buildPreview||this.buildPreview.texture.key!==p.texture){this.buildPreview?.destroy();this.buildPreview=this.add.image(0,0,p.texture).setOrigin(.5,1).setDepth(1901).setAlpha(.72)}this.buildPreview.setPosition(centerX,bottomY).setDisplaySize(p.display.w,p.display.h).setAngle(p.rotation).setTint(valid?0x9dffba:0xff8a80)}else{this.buildPreview?.destroy();this.buildPreview=null}}
 showInstalledEnrichment(i){const w=Math.max(1,...i.cells.map(t=>t.c-i.c+1))*32,s=this.add.image(i.x+(w-32)/2,i.y,'items',ITEM[i.itemId]??0).setDisplaySize(Math.min(w,58),42).setDepth(110+i.y);s.placed=i;this.enrichmentSprites.push(s);for(const t of i.cells){const p=this.grid.center(t.c,t.r),z=this.add.zone(p.x,p.y,28,24);this.physics.add.existing(z,true);this.walls.add(z)}return s}
 animalPath(s,cell){const start=this.grid.cell(s.x,s.y);s.brain.path=this.grid.path(start,cell,(c,r)=>this.grid.animalWalkable(s.animal.species,c,r));s.brain.pathIndex=Math.min(1,s.brain.path.length-1)}
 chooseActivity(s,time){const pen=this.game.app.pens.penFor(s.animal.species),points=this.game.app.pens.availablePoints(s.animal.species);let options=points.filter(p=>!['food','water'].includes(p.kind));if(s.animal.hunger<72)options.push(...points.filter(p=>p.kind==='food'));if(Math.random()<.2)options.push(...points.filter(p=>p.kind==='water'));if(options.length&&Math.random()<.58){const p=Phaser.Utils.Array.GetRandom(options);if(this.game.app.pens.reserve(pen.id,p.pointId,s.animal.id)){s.brain.reservation={penId:pen.id,pointId:p.pointId,kind:p.kind};this.animalPath(s,{c:p.c,r:p.r});s.brain.state='toActivity';s.brain.until=time+9000;return}}const target=Phaser.Utils.Array.GetRandom(pen.interiorCells);this.animalPath(s,target);s.brain.state='wander';s.brain.until=time+6500}
 pose(s,p){const c=p==='rest'?s.meta.cols-3:p==='eat'?s.meta.cols-2:p==='special'?s.meta.cols-1:0;s.setFrame(s.baseFrame+c).setFlipX(false)}
 walkFrame(s,dx,dy,time){if(time>s.brain.frameAt){s.brain.toggle=1-s.brain.toggle;s.brain.frameAt=time+220}const horizontal=Math.abs(dx)>Math.abs(dy),c=animalWalkColumn(s.animal.species,dx,dy,s.brain.toggle);s.setFlipX(horizontal&&(s.animal.species==='Rabbit'?dx<0:dx>0));s.setFrame(s.baseFrame+Math.min(c,s.meta.cols-1))}
 updateAnimals(time){for(const s of this.animalSprites){const q=s.brain;if(['idle','activity'].includes(q.state)&&time>=q.until){if(q.reservation){this.game.app.pens.release(q.reservation.penId,q.reservation.pointId,s.animal.id);q.reservation=null}this.chooseActivity(s,time)}if(['wander','toActivity'].includes(q.state)&&q.path.length){const cell=q.path[q.pathIndex],p=this.grid.center(cell.c,cell.r),dx=p.x-s.x,dy=p.y-s.y,d=Math.hypot(dx,dy);if(d<4){if(q.pathIndex<q.path.length-1)q.pathIndex++;else{q.path=[];s.setVelocity(0);if(q.state==='toActivity'){q.state='activity';q.until=time+2200+Math.random()*2600;const k=q.reservation?.kind;this.pose(s,['food','water','puzzle'].includes(k)?'eat':k==='bed'?'rest':'special');if(['play','scratch','tunnel','chew','puzzle'].includes(k))s.animal.happiness=Math.min(100,s.animal.happiness+8);if(k==='food')s.animal.hunger=Math.min(100,s.animal.hunger+12)}else{q.state='idle';q.until=time+1200+Math.random()*3000;this.pose(s,'idle')}}}else{let vx=dx/d*s.meta.speed,vy=dy/d*s.meta.speed;for(const o of this.animalSprites){if(o===s||o.animal.species!==s.animal.species)continue;const ox=s.x-o.x,oy=s.y-o.y,od=Math.hypot(ox,oy),min=s.bodyRadius+o.bodyRadius+3;if(od>0&&od<min){vx+=ox/od*24;vy+=oy/od*24}}s.setVelocity(vx,vy);this.walkFrame(s,vx,vy,time)}}else s.setVelocity(0);s.setDepth(100+s.y)}}
 claimView(species,id){for(const t of VIEWING[species]){const k=`${t.c},${t.r}`;if(!this.viewReservations.has(k)&&this.grid.publicWalkable(t.c,t.r)){this.viewReservations.set(k,id);return{...t,key:k,species}}}return null}
 visitorGoals(id){const picks=Phaser.Utils.Array.Shuffle(Object.keys(VIEWING)),claims=[];for(const species of picks){const c=this.claimView(species,id);if(c)claims.push(c);if(claims.length===2)break}return{claims,goals:[DESTINATIONS.lobby,...claims.map(c=>({...c,pause:true})),DESTINATIONS.lobby,DESTINATIONS.exit]}}
 setVisitorPath(s,goal){const start=this.grid.cell(s.x,s.y);s.currentGoal=goal;s.path=this.grid.path(start,goal,(c,r)=>this.grid.npcWalkable(c,r));s.pathIndex=Math.min(1,s.path.length-1);s.lastProgress={x:s.x,y:s.y,time:this.time.now}}
 spawnVisitor(adopter=false){const row=Math.floor(Math.random()*4),id=Phaser.Utils.String.UUID(),plan=this.visitorGoals(id),start=worldCenter(19,22),s=this.physics.add.sprite(start.x,start.y,'npc-actions',row*10).setDisplaySize(54*(.95+Math.random()*.1),84*(.95+Math.random()*.1));s.id=id;s.body.setSize(58,42).setOffset(56,205);s.kind='visitor';s.isAdopter=adopter;s.visitor=adopter?this.game.app.adoption.generate():null;s.goals=plan.goals;s.viewClaims=plan.claims;s.goalIndex=0;s.pauseUntil=0;s.npcBase=row*10;this.visitors.push(s);this.setVisitorPath(s,s.goals[0]);this.physics.add.collider(s,this.walls);this.physics.add.collider(s,this.player);if(adopter)s.bubble=this.add.text(0,0,'♥',{fontSize:'18px',backgroundColor:'#fff3d0',color:'#c84f4f',padding:{x:5,y:2}}).setOrigin(.5).setDepth(1000);return s}
 personWalk(s,vx,vy,time,base){if(time<(s.walkAt||0))return;s.walkAt=time+180;s.walkToggle=1-(s.walkToggle||0);let c;if(s===this.player&&Math.abs(vx)>Math.abs(vy)){c=7+s.walkToggle;s.setFlipX(vx<0)}else if(Math.abs(vx)>Math.abs(vy)){c=(vx<0?5:7)+s.walkToggle;s.setFlipX(false)}else{c=(vy<0?3:1)+s.walkToggle;s.setFlipX(false)}s.setFrame(base+c)}
 releaseViews(s){for(const c of s.viewClaims||[])if(this.viewReservations.get(c.key)===s.id)this.viewReservations.delete(c.key)}
 advanceVisitor(s,time){const goal=s.goals[s.goalIndex];if(goal?.pause)s.pauseUntil=time+2200+Math.random()*1500;s.goalIndex++;if(s.goalIndex>=s.goals.length){this.releaseViews(s);s.bubble?.destroy();s.destroy();this.visitors=this.visitors.filter(v=>v!==s);return}this.setVisitorPath(s,s.goals[s.goalIndex])}
 updateVisitors(time){for(const s of [...this.visitors]){if(s.pauseUntil>time){s.setVelocity(0);s.setFrame(s.npcBase);continue}const cell=s.path[s.pathIndex];if(!cell){this.advanceVisitor(s,time);continue}const p=this.grid.center(cell.c,cell.r),dx=p.x-s.x,dy=p.y-s.y,d=Math.hypot(dx,dy);if(d<5){if(s.pathIndex<s.path.length-1)s.pathIndex++;else this.advanceVisitor(s,time)}else{let vx=dx/d*72,vy=dy/d*72;for(const o of this.visitors){if(o===s)continue;const ox=s.x-o.x,oy=s.y-o.y,od=Math.hypot(ox,oy);if(od>0&&od<34){vx+=ox/od*20;vy+=oy/od*20}}s.setVelocity(vx,vy);this.personWalk(s,vx,vy,time,s.npcBase)}if(Phaser.Math.Distance.Between(s.x,s.y,s.lastProgress.x,s.lastProgress.y)>9)s.lastProgress={x:s.x,y:s.y,time};else if(time-s.lastProgress.time>1500){this.setVisitorPath(s,s.currentGoal);if(!s.path.length){s.currentGoal=Phaser.Utils.Array.GetRandom(SAFE_WAIT);this.setVisitorPath(s,s.currentGoal)}}s.setDepth(300+s.y);if(s.bubble)s.bubble.setPosition(s.x,s.y-52)}}
 nearest(){let best=null,dist=150;for(const c of [...this.animalSprites,...this.objects,...this.visitors.filter(v=>v.isAdopter)]){const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,c.x,c.y);if(d<dist){best=c;dist=d}}return best}
 removeAnimal(id){const s=this.animalSprites.find(x=>x.animal.id===id);if(s){if(s.brain.reservation)this.game.app.pens.release(s.brain.reservation.penId,s.brain.reservation.pointId,id);s.destroy();this.animalSprites=this.animalSprites.filter(x=>x!==s)}}
 toggleDebug(){this.debugEnabled=!this.debugEnabled;if(!this.debugGraphics)this.debugGraphics=this.add.graphics().setDepth(2000);this.drawDebug();this.game.app.ui.toast(`Debug grid ${this.debugEnabled?'ON':'OFF'} (F2)`) }
 drawDebug(){const g=this.debugGraphics;g.clear();if(!this.debugEnabled)return;g.lineStyle(1,0xffffff,.18);for(let c=0;c<=COLS;c++)g.lineBetween(c*TILE_SIZE,0,c*TILE_SIZE,WORLD.height);for(let r=0;r<=ROWS;r++)g.lineBetween(0,r*TILE_SIZE,WORLD.width,r*TILE_SIZE);for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++){const p=this.grid.center(c,r),type=this.grid.type(c,r),pen=Object.values(PENS).find(q=>q.interior.some(t=>t.c===c&&t.r===r));if(type!=='floor')g.fillStyle(type==='gate'?0xffcc33:type==='furniture'?0xff7733:0xff3344,.32).fillRect(c*32,r*32,32,32);else if(pen)g.fillStyle(0x55ff88,.18).fillRect(c*32,r*32,32,32);else if(this.grid.npcWalkable(c,r))g.fillStyle(0x3399ff,.14).fillRect(c*32,r*32,32,32)}g.lineStyle(2,0xffff44,.9);for(const v of this.visitors){g.beginPath();g.moveTo(v.x,v.y);for(let i=v.pathIndex;i<v.path.length;i++){const p=this.grid.center(v.path[i].c,v.path[i].r);g.lineTo(p.x,p.y)}g.strokePath();if(v.currentGoal){const p=this.grid.center(v.currentGoal.c,v.currentGoal.r);g.strokeCircle(p.x,p.y,8)}}g.lineStyle(2,0xff66ff,.9);for(const k of this.viewReservations.keys()){const[c,r]=k.split(',').map(Number),p=this.grid.center(c,r);g.strokeRect(p.x-12,p.y-12,24,24)}g.lineStyle(1,0x66ffff,.9);for(const s of this.animalSprites)g.strokeCircle(s.x,s.y,s.bodyRadius);for(const z of this.objects)g.strokeRect(z.x-z.width/2,z.y-z.height/2,z.width,z.height)}
 update(time){if(!this.player||this.scene.isPaused())return;if(this.buildMode){const pan=8/this.cameras.main.zoom;if(this.cursors.left.isDown)this.cameras.main.scrollX-=pan;if(this.cursors.right.isDown)this.cameras.main.scrollX+=pan;if(this.cursors.up.isDown)this.cameras.main.scrollY-=pan;if(this.cursors.down.isDown)this.cameras.main.scrollY+=pan;return}let x=0,y=0;if(this.keys.A.isDown||this.cursors.left.isDown)x=-1;if(this.keys.D.isDown||this.cursors.right.isDown)x=1;if(this.keys.W.isDown||this.cursors.up.isDown)y=-1;if(this.keys.S.isDown||this.cursors.down.isDown)y=1;if(!x&&!y&&time<this.tapUntil){x=this.tapDirection.x;y=this.tapDirection.y}const v=new Phaser.Math.Vector2(x,y).normalize().scale(170);this.player.setVelocity(v.x,v.y);if(x||y)this.personWalk(this.player,v.x,v.y,time,0);else this.player.setFrame(0);this.player.setDepth(300+this.player.y);this.updateAnimals(time);this.updateVisitors(time);if(this.debugEnabled)this.drawDebug();const t=this.nearest();this.game.app.currentTarget=t;this.game.app.ui.prompt(t?(t.kind==='animal'?`Meet ${t.animal.name}`:t.kind==='visitor'?`Talk to ${t.visitor.name}`:t.label):'')}
}

