import Phaser from 'phaser';
import {COLLIDERS,INTERACTIONS,VIEWING_SPOTS,NAV_NODES,NAV_EDGES} from '../data/shelterLayout.js';
const ROW={Dog:{golden:0,black:1,brown:2,spotted:3},Cat:{tuxedo:0,tabby:1,gray:2,calico:3},Rabbit:{white:0,brown:1,spotted:2,gray:3}};
const META={Dog:{texture:'dogs',cols:12,size:64,radius:22,speed:34},Cat:{texture:'cats',cols:12,size:49,radius:17,speed:38},Rabbit:{texture:'rabbits',cols:13,size:37,radius:13,speed:42}};
const ITEM={'tennis-ball':0,'dog-chew':1,'dog-bed':6,'dog-puzzle':7,'scratching-post':2,'cat-tower':2,'cat-toy':3,'cat-bed':6,'cat-puzzle':7,'rabbit-tunnel':4,'rabbit-chew':5,'rabbit-hideout':4,'rabbit-mat':6,'rabbit-puzzle':7};
export class ShelterScene extends Phaser.Scene{
 constructor(){super('Shelter')}
 preload(){this.load.image('floor','./assets/environment/v3/floor.png');this.load.image('structure','./assets/environment/v3/structure-back.png');this.load.image('furniture','./assets/environment/v3/furniture-decoration.png');this.load.image('fences','./assets/environment/v3/pen-foreground.png');this.load.spritesheet('dogs','./assets/sprites/dogs-actions.png',{frameWidth:180,frameHeight:222});this.load.spritesheet('cats','./assets/sprites/cats-actions.png',{frameWidth:200,frameHeight:222});this.load.spritesheet('rabbits','./assets/sprites/rabbits-actions.png',{frameWidth:160,frameHeight:256});this.load.spritesheet('player-actions','./assets/sprites/player-actions.png',{frameWidth:270,frameHeight:724});this.load.spritesheet('npc-actions','./assets/sprites/npc-actions.png',{frameWidth:170,frameHeight:256});this.load.spritesheet('items','./assets/items/enrichment-atlas.png',{frameWidth:362,frameHeight:362})}
 create(){this.add.image(600,360,'floor').setDisplaySize(1200,720).setDepth(0);this.add.image(600,360,'structure').setDisplaySize(1200,720).setDepth(40);this.add.image(600,360,'furniture').setDisplaySize(1200,720).setDepth(80);this.physics.world.setBounds(12,12,1176,696);this.objects=[];this.animalSprites=[];this.visitors=[];this.enrichmentSprites=[];this.viewReservations=new Map();this.debugEnabled=false;this.createCollision();this.createObjects();this.createAnimals();this.createPlayer();this.add.image(600,360,'fences').setDisplaySize(1200,720).setDepth(900);this.keys=this.input.keyboard.addKeys('W,A,S,D');this.cursors=this.input.keyboard.createCursorKeys();this.tapDirection=new Phaser.Math.Vector2();this.tapUntil=0;this.input.keyboard.on('keydown',e=>{const d={ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0],ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1]}[e.key];if(d){this.tapDirection.set(...d);this.tapUntil=this.time.now+110}});this.input.keyboard.on('keydown-F2',()=>this.toggleDebug());this.time.addEvent({delay:4000,loop:true,callback:()=>{this.game.app.animals.tick(1,this.game.app.pens);this.game.app.ui.refresh()}});this.time.addEvent({delay:22000,loop:true,callback:()=>this.game.app.queueIntake()});this.time.delayedCall(2500,()=>this.spawnVisitor(true));this.time.addEvent({delay:11000,loop:true,callback:()=>{if(this.visitors.length<5)this.spawnVisitor(Math.random()<.35)}})}
 createCollision(){this.walls=this.physics.add.staticGroup();this.collisionDefs=[];for(const d of COLLIDERS){const z=this.add.zone(d.x,d.y,d.w,d.h);this.physics.add.existing(z,true);this.walls.add(z);this.collisionDefs.push(d)}}
 addZone(x,y,w,h,type,label){const z=this.add.zone(x,y,w,h);z.kind='object';z.type=type;z.label=label;this.objects.push(z);return z}
 createObjects(){for(const z of INTERACTIONS)this.addZone(z.x,z.y,z.w,z.h,z.type,z.label)}
 createAnimals(){this.animalGroup=this.physics.add.group();for(const a of this.game.app.animals.animals)this.spawnAnimal(a,this.openSpot(a.species));for(const p of Object.values(this.game.app.pens.pens))for(const i of p.installed)this.showInstalledEnrichment(i)}
 openSpot(species){const p=this.game.app.pens.penFor(species),m=META[species],same=this.animalSprites.filter(s=>s.animal.species===species);for(let i=0;i<50;i++){const x=p.bounds.x+m.radius+Math.random()*(p.bounds.width-m.radius*2),y=p.bounds.y+m.radius+Math.random()*(p.bounds.height-m.radius*2);if(same.every(s=>Phaser.Math.Distance.Between(x,y,s.x,s.y)>m.radius+s.bodyRadius+5))return[x,y]}return[p.bounds.x+m.radius+same.length*(m.radius*2+8),p.bounds.y+m.radius]}
 spawnAnimal(animal,[x,y]){const m=META[animal.species],base=(ROW[animal.species][animal.appearance.id]??0)*m.cols,scale=.94+Math.random()*.12,s=this.physics.add.sprite(x,y,m.texture,base).setDisplaySize(m.size*scale,m.size*scale);s.body.setCircle(m.radius*.72,undefined,m.radius*.55);s.kind='animal';s.animal=animal;s.bodyRadius=m.radius;s.meta=m;s.baseFrame=base;s.brain={state:'idle',until:this.time.now+1000+Math.random()*3000,target:null,reservation:null,frameAt:0,toggle:0};this.animalSprites.push(s);this.animalGroup.add(s);this.physics.add.collider(s,this.animalGroup);return s}
 createPlayer(){const s=this.physics.add.sprite(600,675,'player-actions',0).setDisplaySize(52,78);s.body.setSize(76,55).setOffset(97,650).setCollideWorldBounds(true);this.player=s;this.physics.add.collider(s,this.walls)}
 showInstalledEnrichment(i){const s=this.add.image(i.x,i.y,'items',ITEM[i.itemId]??0).setDisplaySize(38,38).setDepth(110+i.y);s.placed=i;this.enrichmentSprites.push(s);return s}
 chooseActivity(s,time){const pen=this.game.app.pens.penFor(s.animal.species),points=this.game.app.pens.availablePoints(s.animal.species);let options=points.filter(p=>!['food','water'].includes(p.kind));if(s.animal.hunger<72)options.push(...points.filter(p=>p.kind==='food'));if(Math.random()<.2)options.push(...points.filter(p=>p.kind==='water'));if(options.length&&Math.random()<.58){const p=Phaser.Utils.Array.GetRandom(options);if(this.game.app.pens.reserve(pen.id,p.pointId,s.animal.id)){s.brain.reservation={penId:pen.id,pointId:p.pointId,kind:p.kind};s.brain.target={x:p.x,y:p.y};s.brain.state='toActivity';s.brain.until=time+9000;return}}if(Math.random()<.62){const b=pen.bounds,r=s.bodyRadius;s.brain.target={x:b.x+r+Math.random()*(b.width-r*2),y:b.y+r+Math.random()*(b.height-r*2)};s.brain.state='wander';s.brain.until=time+6500}else{s.brain.state='idle';s.brain.until=time+1800+Math.random()*4000;this.pose(s,Math.random()<.45?'rest':'idle')}}
 pose(s,p){const c=p==='rest'?s.meta.cols-3:p==='eat'?s.meta.cols-2:p==='special'?s.meta.cols-1:0;s.setFrame(s.baseFrame+c).setFlipX(false)}
 walkFrame(s,dx,dy,time){if(time>s.brain.frameAt){s.brain.toggle=1-s.brain.toggle;s.brain.frameAt=time+220}let c;if(Math.abs(dx)>Math.abs(dy)){c=(s.animal.species==='Rabbit'?7:6)+s.brain.toggle;s.setFlipX(dx<0)}else if(dy<0){c=4+s.brain.toggle;s.setFlipX(false)}else{c=1+s.brain.toggle;s.setFlipX(false)}s.setFrame(s.baseFrame+Math.min(c,s.meta.cols-1))}
 updateAnimals(time){for(const s of this.animalSprites){const q=s.brain,pen=this.game.app.pens.penFor(s.animal.species),b=pen.bounds,r=s.bodyRadius;if(['idle','activity'].includes(q.state)&&time>=q.until){if(q.reservation){this.game.app.pens.release(q.reservation.penId,q.reservation.pointId,s.animal.id);q.reservation=null}this.chooseActivity(s,time)}if(['wander','toActivity'].includes(q.state)){const dx=q.target.x-s.x,dy=q.target.y-s.y,d=Math.hypot(dx,dy);if(d<5){s.setVelocity(0);if(q.state==='toActivity'){q.state='activity';q.until=time+2200+Math.random()*2600;const k=q.reservation?.kind;this.pose(s,['food','water','puzzle'].includes(k)?'eat':k==='bed'?'rest':'special');if(['play','scratch','tunnel','chew','puzzle'].includes(k))s.animal.happiness=Math.min(100,s.animal.happiness+8);if(k==='food')s.animal.hunger=Math.min(100,s.animal.hunger+12)}else{q.state='idle';q.until=time+1200+Math.random()*3500;this.pose(s,'idle')}}else{let vx=dx/d*s.meta.speed,vy=dy/d*s.meta.speed;for(const o of this.animalSprites){if(o===s||o.animal.species!==s.animal.species)continue;const ox=s.x-o.x,oy=s.y-o.y,od=Math.hypot(ox,oy),min=r+o.bodyRadius+4;if(od>0&&od<min){vx+=ox/od*28;vy+=oy/od*28}}s.setVelocity(vx,vy);this.walkFrame(s,vx,vy,time)}}else s.setVelocity(0);s.x=Phaser.Math.Clamp(s.x,b.x+r,b.x+b.width-r);s.y=Phaser.Math.Clamp(s.y,b.y+r,b.y+b.height-r);s.setDepth(100+s.y)}}
 claimView(species,id){for(let i=0;i<VIEWING_SPOTS[species].length;i++){const key=`${species}-${i}`;if(!this.viewReservations.has(key)){this.viewReservations.set(key,id);return{key,point:VIEWING_SPOTS[species][i]}}}return null}
 point(name,lane=0){const usesLane=['entrance','lobby','hallCenter'].includes(name);return{x:NAV_NODES[name][0]+(usesLane?lane:0),y:NAV_NODES[name][1],name}}
 buildRoute(id,lane){const species=Phaser.Utils.Array.Shuffle(Object.keys(VIEWING_SPOTS)).slice(0,2),claims=species.map(s=>this.claimView(s,id)).filter(Boolean),r=[this.point('entrance',lane),this.point('lobby',lane),this.point('hallCenter',lane)];for(const c of claims){const branch=c.key.startsWith('Dog')?'hallLeft':c.key.startsWith('Rabbit')?'hallRight':null;if(branch)r.push(this.point(branch));r.push({x:c.point[0],y:c.point[1],pause:true});if(branch)r.push(this.point(branch));r.push(this.point('hallCenter',lane))}r.push(this.point('lobby',lane),this.point('entrance',lane),{x:600+lane,y:716,exit:true});return{route:r,claims}}
 releaseViews(s){for(const c of s.viewClaims||[])if(this.viewReservations.get(c.key)===s.id)this.viewReservations.delete(c.key)}
 spawnVisitor(adopter=false){const row=Math.floor(Math.random()*4),id=Phaser.Utils.String.UUID(),lane=(this.visitors.length%3-1)*22,plan=this.buildRoute(id,lane),s=this.physics.add.sprite(600+lane,716,'npc-actions',row*10).setDisplaySize(54*(.95+Math.random()*.1),84*(.95+Math.random()*.1));s.id=id;s.body.setSize(58,42).setOffset(56,205);s.kind='visitor';s.isAdopter=adopter;s.visitor=adopter?this.game.app.adoption.generate():null;s.route=plan.route;s.viewClaims=plan.claims;s.routeIndex=0;s.pauseUntil=0;s.lastProgress={x:s.x,y:s.y,time:this.time.now};s.npcBase=row*10;this.visitors.push(s);this.physics.add.collider(s,this.walls);this.physics.add.collider(s,this.player);if(adopter)s.bubble=this.add.text(0,0,'♥',{fontSize:'18px',backgroundColor:'#fff3d0',color:'#c84f4f',padding:{x:5,y:2}}).setOrigin(.5).setDepth(1000);return s}
 personWalk(s,vx,vy,time,base){if(time<(s.walkAt||0))return;s.walkAt=time+180;s.walkToggle=1-(s.walkToggle||0);let c;if(s===this.player&&Math.abs(vx)>Math.abs(vy)){c=7+s.walkToggle;s.setFlipX(vx<0)}else if(Math.abs(vx)>Math.abs(vy)){c=(vx<0?5:7)+s.walkToggle;s.setFlipX(false)}else{c=(vy<0?3:1)+s.walkToggle;s.setFlipX(false)}s.setFrame(base+c)}
 updateVisitors(time){for(const s of [...this.visitors]){if(s.pauseUntil>time){s.setVelocity(0);s.setFrame(s.npcBase);continue}const p=s.route[s.routeIndex];if(!p)continue;const d=Phaser.Math.Distance.Between(s.x,s.y,p.x,p.y);if(d<10){s.routeIndex++;if(p.pause)s.pauseUntil=time+2200+Math.random()*1600;if(p.exit){this.releaseViews(s);s.bubble?.destroy();s.destroy();this.visitors=this.visitors.filter(v=>v!==s);continue}}else{this.physics.moveTo(s,p.x,p.y,70);this.personWalk(s,s.body.velocity.x,s.body.velocity.y,time,s.npcBase)}if(Phaser.Math.Distance.Between(s.x,s.y,s.lastProgress.x,s.lastProgress.y)>10)s.lastProgress={x:s.x,y:s.y,time};else if(time-s.lastProgress.time>1700){s.routeIndex=Math.min(s.routeIndex+1,s.route.length-1);s.lastProgress={x:s.x,y:s.y,time}}s.setDepth(300+s.y);if(s.bubble)s.bubble.setPosition(s.x,s.y-52)}}
 nearest(){let best=null,dist=150;for(const c of [...this.animalSprites,...this.objects,...this.visitors.filter(v=>v.isAdopter)]){const d=Phaser.Math.Distance.Between(this.player.x,this.player.y,c.x,c.y);if(d<dist){best=c;dist=d}}return best}
 removeAnimal(id){const s=this.animalSprites.find(x=>x.animal.id===id);if(s){if(s.brain.reservation)this.game.app.pens.release(s.brain.reservation.penId,s.brain.reservation.pointId,id);s.destroy();this.animalSprites=this.animalSprites.filter(x=>x!==s)}}
 toggleDebug(){this.debugEnabled=!this.debugEnabled;if(!this.debugGraphics)this.debugGraphics=this.add.graphics().setDepth(2000);this.drawDebug();this.game.app.ui.toast(`Debug overlays ${this.debugEnabled?'ON':'OFF'} (F2)`) }
 drawDebug(){const g=this.debugGraphics;g.clear();if(!this.debugEnabled)return;g.lineStyle(2,0xff5252,.9);for(const d of this.collisionDefs)g.strokeRect(d.x-d.w/2,d.y-d.h/2,d.w,d.h);g.lineStyle(2,0x55ff88,.95);for(const p of Object.values(this.game.app.pens.pens)){g.strokeRect(p.bounds.x,p.bounds.y,p.bounds.width,p.bounds.height);for(const q of [...p.bowlSlots,...p.installed.map(i=>i.interaction)])g.strokeCircle(q.x,q.y,7)}g.lineStyle(1,0x66ccff,.8);for(const[a,links]of Object.entries(NAV_EDGES))for(const b of links){g.beginPath();g.moveTo(...NAV_NODES[a]);g.lineTo(...NAV_NODES[b]);g.strokePath()}for(const s of this.animalSprites)g.strokeCircle(s.x,s.y,s.bodyRadius);g.lineStyle(1,0xffff66,.8);for(const v of this.visitors){g.beginPath();g.moveTo(v.x,v.y);for(let i=v.routeIndex;i<v.route.length;i++)g.lineTo(v.route[i].x,v.route[i].y);g.strokePath()}g.fillStyle(0xffff00,.25);for(const z of this.objects)g.fillRect(z.x-z.width/2,z.y-z.height/2,z.width,z.height)}
 update(time){if(!this.player||this.scene.isPaused())return;let x=0,y=0;if(this.keys.A.isDown||this.cursors.left.isDown)x=-1;if(this.keys.D.isDown||this.cursors.right.isDown)x=1;if(this.keys.W.isDown||this.cursors.up.isDown)y=-1;if(this.keys.S.isDown||this.cursors.down.isDown)y=1;if(!x&&!y&&time<this.tapUntil){x=this.tapDirection.x;y=this.tapDirection.y}const v=new Phaser.Math.Vector2(x,y).normalize().scale(170);this.player.setVelocity(v.x,v.y);if(x||y)this.personWalk(this.player,v.x,v.y,time,0);else this.player.setFrame(0);this.player.setDepth(300+this.player.y);this.updateAnimals(time);this.updateVisitors(time);if(this.debugEnabled)this.drawDebug();const t=this.nearest();this.game.app.currentTarget=t;this.game.app.ui.prompt(t?(t.kind==='animal'?`Meet ${t.animal.name}`:t.kind==='visitor'?`Talk to ${t.visitor.name}`:t.label):'')}
}

