import Phaser from 'phaser';import './style.css';import {ShelterScene} from './scenes/ShelterScene.js';import {AnimalSystem} from './systems/AnimalSystem.js';import {EconomySystem} from './systems/EconomySystem.js';import {ObjectiveSystem} from './systems/ObjectiveSystem.js';import {AdoptionSystem} from './systems/AdoptionSystem.js';import {IntakeSystem} from './systems/IntakeSystem.js';import {EnrichmentSystem} from './systems/EnrichmentSystem.js';import {PenSystem} from './systems/PenSystem.js';import {GridSystem} from './systems/GridSystem.js';import {UIManager} from './ui/UIManager.js';
class PawHaven{
 constructor(){this.animals=new AnimalSystem();this.animals.seed();this.economy=new EconomySystem();this.objectives=new ObjectiveSystem();this.adoption=new AdoptionSystem();this.adoption.generate();this.grid=new GridSystem();this.pens=new PenSystem(this.animals,this.grid);this.intake=new IntakeSystem(this.animals,this.pens);this.enrichment=new EnrichmentSystem(this.economy,this.pens);this.intake.generate();this.intake.generate();this.game=new Phaser.Game({type:Phaser.AUTO,parent:'game',backgroundColor:'#152821',pixelArt:true,antialias:false,roundPixels:true,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH,width:1216,height:736},physics:{default:'arcade',arcade:{debug:false}},scene:[ShelterScene]});this.game.app=this;this.ui=new UIManager(this);this.ui.refresh();document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='e'&&!document.querySelector('.modal-backdrop')&&!document.querySelector('#title-screen:not(.hidden)'))this.interact(this.currentTarget)})}
 get scene(){return this.game.scene.getScene('Shelter')}
 start(){document.querySelector('#title-screen').classList.add('hidden');this.ui.showHUD();this.ui.toast('Shelter open! Check the intake computer.')}
 interact(target){if(!target)return;if(target.kind==='animal')this.ui.profile(target.animal);else if(target.kind==='visitor'||target.type==='desk')this.ui.adoption(target.visitor||this.adoption.visitor,this.animals.animals);else if(target.type==='computer')this.ui.computer();else this.ui.toast(target.type==='food'?'The pantry is stocked with food and supplies.':'Fresh towels and cleaning supplies are ready.')}
 care(animal,action){const costs={feed:3,clean:2,play:0,medicate:5};if(!this.economy.spend(costs[action]))return this.ui.toast('Not enough funds.');const stat=this.animals.care(animal,action);this.objectives.complete(action);this.ui.refresh();this.ui.toast(`${animal.name}'s ${stat} improved!`);this.ui.close();setTimeout(()=>this.ui.profile(animal),0)}
 completeAdoption(id){const animal=this.animals.animals.find(a=>a.id===id);if(!animal)return;const score=this.adoption.score(animal);const reward=this.economy.adoption(score);this.objectives.complete('adopt');this.animals.remove(id);this.scene.removeAnimal(id);this.ui.refresh();this.ui.adoptionResult(animal,score,reward);this.adoption.generate();this.scene.visitors.filter(v=>v.isAdopter).forEach(v=>{v.bubble?.destroy();v.isAdopter=false});this.scene.time.delayedCall(5000,()=>this.queueIntake())}
 queueIntake(){if(this.intake.pending.length>=3)return;const a=this.intake.generate();this.ui.toast(`New intake request: ${a.name} the ${a.species.toLowerCase()}`)}
 acceptIntake(id){const animal=this.intake.accept(id);if(!animal){this.ui.toast('That species pen is at capacity.');return}this.scene.spawnAnimal(animal,this.scene.openSpot(animal.species));this.ui.toast(`${animal.name} has joined the shelter!`);this.ui.computer('intake')}
 declineIntake(id){this.intake.decline(id);this.ui.toast('Intake request declined.');this.ui.computer('intake')}
 buyEnrichment(id){const item=this.enrichment.purchase(id);if(!item){this.ui.toast('Not enough shelter funds.');return}this.ui.refresh();this.ui.toast(`${item.name} added to the supply cart.`);this.ui.computer('shop')}
 installEnrichment(index,species){const itemId=this.enrichment.inventory[index],placed=this.enrichment.install(itemId,species);if(!placed){this.ui.toast(`The ${species.toLowerCase()} pen has no compatible open enrichment tiles.`);return}this.scene.showInstalledEnrichment(placed);this.ui.toast(`Installed in the ${species.toLowerCase()} pen!`);this.ui.computer('inventory')}
}
const app=new PawHaven();window.pawHaven=app;document.querySelector('#start-button').addEventListener('click',()=>app.start());

