import Phaser from 'phaser';import './style.css';import {ShelterScene} from './scenes/ShelterScene.js';import {AnimalSystem} from './systems/AnimalSystem.js';import {EconomySystem} from './systems/EconomySystem.js';import {ObjectiveSystem} from './systems/ObjectiveSystem.js';import {AdoptionSystem} from './systems/AdoptionSystem.js';import {UIManager} from './ui/UIManager.js';
class PawHaven{
  constructor(){this.animals=new AnimalSystem();this.animals.seed();this.economy=new EconomySystem();this.objectives=new ObjectiveSystem();this.adoption=new AdoptionSystem();this.adoption.generate();this.game=new Phaser.Game({type:Phaser.AUTO,parent:'game',backgroundColor:'#eee4c6',scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH,width:1200,height:720},physics:{default:'arcade',arcade:{debug:false}},scene:[ShelterScene]});this.game.app=this;this.ui=new UIManager(this);this.ui.refresh();document.addEventListener('keydown',event=>{if(event.key.toLowerCase()==='e'&&!document.querySelector('.modal-backdrop')&&!document.querySelector('#title-screen:not(.hidden)'))this.interact(this.currentTarget)})}
  get scene(){return this.game.scene.getScene('Shelter')}
  start(){document.querySelector('#title-screen').classList.add('hidden');this.ui.showHUD();this.ui.toast('Shelter open! Go meet an animal.')}
  interact(target){if(!target)return;if(target.kind==='animal')this.ui.profile(target.animal);else if(target.type==='desk')this.ui.adoption(this.adoption.visitor,this.animals.animals);else this.ui.toast(target.type==='food'?'Food pantry stocked and ready.':'Clean towels and supplies are ready.')}
  care(animal,action){const costs={feed:3,clean:2,play:0,medicate:5};if(!this.economy.spend(costs[action])){this.ui.toast('Not enough funds.');return}const stat=this.animals.care(animal,action);this.objectives.complete(action);this.ui.refresh();this.ui.toast(`${animal.name}'s ${stat} improved!`);this.ui.close();setTimeout(()=>this.ui.profile(animal),0)}
  completeAdoption(id){const animal=this.animals.animals.find(a=>a.id===id);const score=this.adoption.score(animal);const reward=this.economy.adoption(score);this.objectives.complete('adopt');this.animals.remove(id);const sprite=this.scene.animalSprites.find(s=>s.animal.id===id);if(sprite){sprite.destroy();this.scene.animalSprites=this.scene.animalSprites.filter(s=>s!==sprite)}this.ui.refresh();this.ui.adoptionResult(animal,score,reward);const species=['Dog','Cat','Rabbit'][Math.floor(Math.random()*3)];this.scene.time.delayedCall(7000,()=>{const newcomer=this.animals.create(species,species.toLowerCase());const spots={Dog:[210,200],Rabbit:[600,200],Cat:[995,200]};this.scene.spawnAnimal(newcomer,spots[species]);this.scene.physics.add.collider(this.scene.player,this.scene.animalSprites.at(-1));this.ui.toast(`${newcomer.name} the ${species.toLowerCase()} just arrived!`)});this.adoption.generate()}
}
const app=new PawHaven();
// Exposing the running app makes browser-based smoke tests and future debugging
// much easier without changing the rules of the game.
window.pawHaven=app;
document.querySelector('#start-button').addEventListener('click',()=>app.start());
